### ISSUE TITLE
Assignment 2: Ex 1.2

### ISSUE THREAD

**Issue by zenoli** [eth-igl/GP2020-Assignments#10]
Igl has a method to compute closest point using AABB trees under the hood:
igl::point_mesh_squared_distance

1. What is the runtime complexity of this function? 
2. May we use this to implement the two queries in ex 1.2?
3. In the first task we already needed to compute closest points when inserting constraint points to make sure that the constraint points are closest to the respective original points. Do we have to use the implementation from task 1.2 to perform the queries in 1.1? If yes, why isn't exercise 1.2 listed before 1.1 as 1.1 depends on it?

**Comment by wsh312** [comment]
Hi,

I would not recommend using the AABB tree in libigl. Implementing the uniform grid (or Kd-tree) is a task of the assignment to practice the coding skills ;) If one doesn't use the uniform grid, the performance will be slow and we will remove points accordingly.

**Comment by zenoli** [comment]
I started implementing the spatial index and some questions arised: 
When I query for the closest point to some point q, it is not guaranteed to find the closest point inside q's bin as can be seen in the first (top) example here:
![IMG_1854](https://user-images.githubusercontent.com/8073528/76960512-ebd72380-691b-11ea-820b-77cc1cffe629.jpg)

There is another point p1 in the same bin as q but the nearest point p2 is in another bin.
My idea was then to instead of only considering q's bin, to extend the search in the 1-bin neighborhood of q (i.e. the 3x3 block around q) but then I saw that this does not solve the problem as can be seen in the lower example (I only show the middle horizontal row of the 3x3 block:)

Again there is a point p1 in the 1-neighborhood but the actual closest point p2 lies in the 2-neighborhood.

I think implementing a working algorithm can get very tedious and I wanted to ask whether we have to do this? Or are we satisfied by only inspecting a constant neighborhood even though theoretically there are instances were the algorithm would fail?

**Comment by zenoli** [comment]
Ok, I found a workaround myself:
If we want to know that a constraint point qi = pi + eps*ni is really closest to pi, we first compute the distance d between these two points. Then we compute all cells which might contain points that are also within distance d, iterate over these cells and check all points in these cells one by one to see if there is a closer point.

So the workaround was not to implement a function `Point getClosestPoint(Point q)` (which I still claim can be very tedious to implement in a general setting) but to implement a function `bool isClosest(Point p, Point q)`.

Hope this helps in case anyone else was struggling :-)
