### ISSUE TITLE
Assignment 2: Ex 2.3 - non-axis aligned bounding box

### ISSUE THREAD

**Issue by Yingyan-Xu** [eth-igl/GP2020-Assignments#11]
Is it sufficient to just apply some transformation on the input points rather than the grid points to obtain an axis-aligned bounding box? While they are conceptually the same, the former approach is more adaptable for my code so far...

**Comment by wsh312** [comment]
Hi, sorry for the delayed reply. 
Yes, I don't think that's a problem as long as the "wasteful" grids can be minimized, which is the goal of using PCA.
