### ISSUE TITLE
Assignment2: Ex1.2

### ISSUE THREAD

**Issue by claire43** [eth-igl/GP2020-Assignments#16]
How do we determine the size of each uniform grid? I was originally thinking of building a uniform grid each time we make a query based on the radius involved in that query, but this way the algorithm will be just as inefficient as brute force. Therefore, how should we pick a resolution/grid size that will work universally for all types of radius queries? Thanks!

**Comment by wsh312** [comment]
Hi, 
This is a limitation of the uniform grid as we discussed, basically, we need to rebuild the grid structure every time we change the radius. But it's still faster than brute-force.

**Comment by zenoli** [comment]
Why would you have to rebuild the grid for different radii? One could simply consider a different neighborhood of cells, no?

**Comment by wsh312** [comment]
Thanks, yes, one can also use dynamic neighbouring cells instead of dynamic cell size.
