### ISSUE TITLE
Bonus clarification

### ISSUE THREAD

**Issue by claire43** [eth-igl/GP2020-Assignments#17]
Sorry if I missed the exercises, but I was wondering which specific parts of the following are the bonus parts of this assignment? It was not specified in the writeup. 
(1) Constraints [1]
(2) Implicit Function [4]
(3) Demo Performance [2]
(4) PCA [1]	
(5) Report [1]
(6) Theory Normals [2]
(7) Theory Deriavtive [2]
(8) Normal Constraint [2] (include implementation [1] and analysis [1])
(9) Theory Poisson [1]
(10) Theory RIMLS [1]

**Comment by yarosskopf** [comment]
My understanding is that there are no bonus-task in this exercise, but they gave us more time. They removed the "optional tasks" in the Readme

https://github.com/eth-igl/GP2020-Assignments/commit/824897bdb6e6121a31c23a4929bd7c661c3cde96

**Comment by wsh312** [comment]
You are right, the exam is removed and we have fewer bonus tasks this year, I hope this makes sense.
