### ISSUE TITLE
Gridpoint value inside mesh

### ISSUE THREAD

**Issue by mattarch** [eth-igl/GP2020-Assignments#18]
Assume there is a gridpoint P within the "sphere.off" mesh. From a theoretical point of view, the gridpoint value should be negative 
If there are no points within the distance of the Wendland radius, it is stated in the assignment, that we should assign a large positive value. However, if the marching cubes algorithm is run, this produces an additional "inner"  mesh. 
Is it expected that we resolve this issue?

**Comment by zenoli** [comment]
+1

**Comment by wsh312** [comment]
Good question. No, we don't expect to solve this issue.
There are ways to compute the sign (inner or outer) like winding number or ray shooting, but it's too much for one assignment. Simple cases like sphere one can use the normal of the closest point to determine the sign. But I guess it's too late to make it as a bonus point ;)
