### ISSUE TITLE
Assignment 4 #3.2 Distortion Visualization

### ISSUE THREAD

**Issue by xxia-kathy** [eth-igl/GP2020-Assignments#24]
Hello, 

I have a few questions about visualization.

Should we be adding colors in only the UV parameterization or both?

Should the coloring be relative to its own distortion or across methods (the latter seems to make more sense to me, but then is there a threshold in which a distortion is considered large and should be red?) 

Thank you!

**Comment by PhHerholz** [comment]
It would be good to add the colors in both views.

You are right, for a comparison across methods it would be good to have a standardized normalization. You are free to do that, however, it is sufficient to normalize the distortion measure for the specific parameterization.

**Comment by xxia-kathy** [comment]
Thank you!
