### ISSUE TITLE
Derivation of Linear System Ex4 p.33

### ISSUE THREAD

**Issue by vyangETH** [eth-igl/GP2020-Assignments#25]
I was trying to derive the linear system on p.33 and came up with this:

where the factor of 2 differs from the equation on the slides. Does this factor matter at all in the implementation? Or would one just get lamdas as a solution that vary by a factor of 2?

**Comment by DanielSparber** [comment]
The constant factor does not really matter. That is probably why it is omitted in the lecture slides.

The lambdas would differ by a factor of 2.
