### ISSUE TITLE
Assignment 4: Eigen::SparseLU fails to initialize

### ISSUE THREAD

**Issue by ioanna21** [eth-igl/GP2020-Assignments#26]
Hi,
In assignment4.pdf it is recommended that we use the `Eigen::SparseLU` to solve the linear system and find the u,v parameters. 

I go through all the steps of initializing the solver, found in the Eigen documentation
```
A.makeCompressed();
solver.analyzePattern(A);
solver.factorize(A);
x = solver.solve(b);
```

However, I get the error: 

`Assertion failed: m_factorizationIsOk && "SparseLU is not initialized.", file I:\Desktop\Google Drive\COURSES\Shape_Modeling\gp20-ioanna21\libigl\external\eigen\Eigen\src/SparseLU/SparseLU.h,`

I also tried using another solver, `Eigen::SparseQR`, that I initialize in the same way. This solver works and I get the results for u,v that look correct. This makes me believe that I have set up the matrices correctly. The problem with the SparseQR is that for the big meshes if freezes and never computes the result.  

Any ideas what might be going wrong and what solver I could use? 

Thanks,
Ioanna

**Comment by DanielSparber** [comment]
Maybe your Matrix is singular. 

The code is fine.

**Comment by ioanna21** [comment]
Thanks for the reply!

It appears that the error comes after the step 
`solver.factorize(A); `

saying 
`THE MATRIX IS STRUCTURALLY SINGULAR ... ZERO COLUMN AT 1`

**Comment by DanielSparber** [comment]
You're welcome!

Just go over the theory again and make sure you construct the matrix in the correct way ;)

**Comment by ioanna21** [comment]
I looked a lot into it, but I couldn't find the solution. I understand the error happens because the matrix A I has some rows that have 0 everywhere. The A consists of the matrices

[A, C_Transposed
 C,  0                   ]

So the 0 rows are coming from the lower part. The matrix C that has the constraints is an identity matrix that has 1 on the diagonal only for the points that are constrained, and 0 everywhere else. Thus leaving many rows with only 0. 
Have I misunderstood how to construct the matrix C, or is there a way to avoid the rows that have 0 everywhere ?

Many thanks!
Ioanna

**Comment by DanielSparber** [comment]
The dimension of C should be numConstraint x 2#V  columns. Maybe that helps?

**Comment by ioanna21** [comment]
Thanks for the answer, yes that helps a lot! I thought that the C was 2#V x 2#V, this resulted in the 0 rows. However, now I am a bit confused about the dimensions of the d vector that stores the positions of the constraint points. 
C [u v] = d 

If  C has dimensions numConstraint x 2#V then the vector d would have dimensions numConstraint x 1. But that is not enough for storing the u and v values of each constraint position.

**Comment by ioanna21** [comment]
Thanks a lot for your reply, it was very helpful. I thought that C was  2#V x 2#V, which produced the 0 rows. Now the problem is solved.

**Comment by DanielSparber** [comment]
d should be 2*numConstraints (number of rows in C)
