### ISSUE TITLE
Assignment 4: Points distribution

### ISSUE THREAD

**Issue by Viturin** [eth-igl/GP2020-Assignments#28]
Hello everyone :)

Could you tell us how the Assignemnt 4 will be graded? i.e. how many points per subtask. 

Thank you very much

**Comment by wsh312** [comment]
![image](https://user-images.githubusercontent.com/4659365/80689613-e26dd900-8acd-11ea-875d-b5e5748de6df.png)
Here is the point distribution last year, we will do slight modification based on the overall performance and make it sum to 17 points.

**Comment by Viturin** [comment]
thank you 😀
