### ISSUE TITLE
Assignment 5, tutorial slides and lectures

### ISSUE THREAD

**Issue by ioanna21** [eth-igl/GP2020-Assignments#29]
Hello, 
I could not find the tutorial slides and lecture for assignment 5 on the igl website, could you please upload them? 

Many thanks,
Ioanna

**Comment by wsh312** [comment]
Hi,
The slides should be on the website, otherwise please try this link: https://www.dropbox.com/s/60zvxgrwkmrglak/ex5_slides.pdf?dl=0

**Comment by ioanna21** [comment]
Great thanks! Is there also a recording of the tutorial?
