### ISSUE TITLE
Vulkan missing

### ISSUE THREAD

**Issue by JonathanLehner** [eth-igl/GP2020-Assignments#3]
On MacOS Mojave I get the error "Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)" when I try to compile with cmake:

-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using Cocoa for window creation
-- Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
-- Creating target: igl::png (igl_png)
-- Creating target: igl::tetgen (igl_tetgen)
-- Creating target: igl::triangle (igl_triangle)
-- Creating target: igl::xml (igl_xml)
CMake Warning at external/googletest/googlemock/CMakeLists.txt:40 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Warning at external/googletest/googletest/CMakeLists.txt:47 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

**Comment by wsh312** [comment]
Hi, 

Maybe you can try:

sudo apt-get install git
sudo apt-get install build-essential
sudo apt-get install cmake
sudo apt-get install libx11-dev
sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
sudo apt-get install libxrandr-dev
sudo apt-get install libxi-dev
sudo apt-get install libxmu-dev
sudo apt-get install libblas-dev
sudo apt-get install libxinerama-dev
sudo apt-get install libxcursor-dev
