### ISSUE TITLE
Assignment 5 - stack smashing detected when rotate

### ISSUE THREAD

**Issue by MarshalLeeeeee** [eth-igl/GP2020-Assignments#30]
Hi, I am wondering if anyone has encountered error "stack smashing detected" when rotate the handle. The program performs well when the handle is translated.
The error happens when mouse is first clicked with mouse_mode as ROTATE.
The program stops at the end of "callback_mouse_down() -> get_new_handle_location()"
I tried to resize system stack size as 100M, but the error still exists.
Thus, does anyone have the same problem or have any advice? Thanks a lot.

**Comment by vyangETH** [comment]
Hi, I'm having the same issue and would be interested in how to solve it:)

**Comment by vyangETH** [comment]
Hey, building in release mode solved the problem for me. So in the assignment5 directory do:

```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j2
```
Best, 
Viviane

**Comment by MarshalLeeeeee** [comment]
That's so cooooooool!!
Thanks a lot, bro!
