### ISSUE TITLE
Assignment 5: Optional Task Source Deformation Gradients

### ISSUE THREAD

**Issue by pandreu** [eth-igl/GP2020-Assignments#32]
In the Deformation Transfer algorithm, one step is computing the source deformation gradients. The paper shows one way of deriving them is with the following formula:

![image](https://user-images.githubusercontent.com/25924223/81553124-ea0e6700-9384-11ea-8dfe-ce82ab277550.png)

In my implementation, I consider the inverse to be taken per element, and that we perform dot products for each of the three vectors independently. In the formula above, I invert each of q1 - q3, q2 - q3 and n element-wise, and then dot product each with their "prime" counterparts.

However, this leads to unstable results: in the woody, for example, all the points initially have the same z coordinate, so the difference of two points will give 0 in the z direction, and dividing later by 0 leads to numerical instability. 

Am I misunderstanding how we compute the source deformation gradients? Or are we supposed to handle these cases somehow?

**Comment by wsh312** [comment]
Hi, in general, it makes sense to treat the zero cases differently.
You may want to borrow ideas from the other implementations:
https://github.com/chand81/Deformation-Transfer/blob/master/src/DeformationTransferManager.cpp
https://github.com/Golevka/deformation-transfer
