### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by JonathanLehner** [eth-igl/GP2020-Assignments#4]
How should we submit the screenshots? As image files or should we summarise them in a pdf? Where should we include them in the git repository?

**Comment by wsh312** [comment]
Hi, you can edit the README.md file directly, for example: 
"
###### Task 3 - Neighborhood computations

| ![](screenshots/t3-neighborhoodComputations/3-1-Vertex-to-Face-Dump.png) | ![](screenshots/t3-neighborhoodComputations/3-2-Vertex-to-Vertex-Dump.png) |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|          Vertex-to-Face relationship of "plane.off"          |         Vertex-to-Vertex relationship of "plane.off"         |"

(the png can be uploaded via git push)

Or maybe you could generate a pdf file using latex and upload it and specify where it is or put a link in in README.md
