### ISSUE TITLE
libigl missing function 

### ISSUE THREAD

**Issue by philianeles** [eth-igl/GP2020-Assignments#5]
Hi, I am missing the function `per_corner_normals()` - is the release of the libigl on the assignment repository up to date? OR any hints how to solve this problem?
Here is the snippet:
![image](https://user-images.githubusercontent.com/11179066/76449081-b6867f00-63cb-11ea-9afc-a73e043c2135.png)

**Comment by wsh312** [comment]
Hi, a quick comment, did you add "#include <igl/per_corner_normals.h>"?

**Comment by philianeles** [comment]
ah, right! Thanks!
