### ISSUE TITLE
Refusing to merge unrelated histories

### ISSUE THREAD

**Issue by huoxiaoyao** [eth-igl/GP2020-Assignments#6]
Dear TAs,
I am getting this error message when trying to pull the code of the second assignment with "git pull base master":
warning: no common commits
remote: Enumerating objects: 1582, done.
remote: Counting objects: 100% (1582/1582), done.
remote: Compressing objects: 100% (1200/1200), done.
remote: Total 1582 (delta 387), reused 1549 (delta 367), pack-reused 0
Receiving objects: 100% (1582/1582), 7.73 MiB | 4.32 MiB/s, done.
Resolving deltas: 100% (387/387), done.
From https://github.com/eth-igl/GP2020-Assignments
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> base/master
fatal: refusing to merge unrelated histories

Do you have any idea how to solve this? Thanks!

**Comment by wsh312** [comment]
Hi, did you commit and push your code, before pull?
If it doesn't work, or there are some wired git problems, I suggest manually download the new assignments, add to your own repository, as if a solo coding project.

**Comment by philianeles** [comment]
Just a comment, I had the same weird problem.
Then I tried `git pull base master --allow-unrelated-histories`. I still had to manually approve a couple of changes but then it worked...maybe it helps.

**Comment by huoxiaoyao** [comment]
thanks philianeles, it worked
